services:
  consul:
    image: hashicorp/consul:latest
    # Wir binden an 0.0.0.0, damit Consul auf JEDER IP innerhalb der Node lauscht
    command: "agent -dev -ui -client=0.0.0.0 -bind=0.0.0.0 -dns-port=53 -disable-host-node-id"
    ports:
      - "8500:8500"
      - "53:53/udp"
      - "8600:8600/udp"
      - "8600:8600/tcp"
    restart: always

  registrator:
    image: gliderlabs/registrator:master
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    # Hier nutzen wir localhost, weil Registrator und Consul in der gleichen Node sind
    command: "-internal consul://172.18.0.2:8500"
    restart: always
    depends_on:
      - consul
