services:
  consul:
    image: hashicorp/consul:latest
    # Wir binden an 0.0.0.0, damit Consul auf JEDER IP innerhalb der Node lauscht
    command: "agent -dev -ui -client=0.0.0.0 -bind=0.0.0.0 -dns-port=53 -disable-host-node-id"
    ports:
      - "8500:8500"
      - "53:53/udp"
      - "8600:8600/udp"
      - "8600:8600/tcp"
    restart: always
 
  log-collector:
    image: my-log-collector
    network_mode: "host"  
    labels:
      - "logspout.exclude=true"  # Das ist die Lebensversicherung!
      #ports:
      #- "514:514/udp"
    environment:
      SERVICE_NAME: log-collector
    restart: always
